---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  
implicit:
  - Пользователь должен иметь возможность выбрать количество товаров
  - Пользователь должен иметь возможность сбросить фильтры товаров
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможномть очистить корзину и продолжить покупку из нее
  - Пользователь должен иметь возможность совершать покупки на сайте 
  - Пользователь должен иметь возможность постранично просматривать товары 
  
